---
namespace: trippsc2
name: mssql
version: 1.3.4
readme: README.md
authors:
  - Jim Tarpley (@trippsc2)
description: This collection contains modules and roles for installing and configuration Microsoft SQL Server.

license_file: 'LICENSE'

tags:
  - database
  - infrastructure
  - linux
  - windows

dependencies:
  ansible.posix: '>=1.0.1'
  ansible.windows: '>=1.0.0'
  chocolatey.chocolatey: '>=1.0.0'
  community.general: '>=6.0.0'
  community.hashi_vault: '>=6.2.0'
  community.windows: '>=1.0.0'
  trippsc2.hashi_vault: '>=1.0.0'
  trippsc2.windows: '>=1.0.0'

repository: https://github.com/trippsoft/ansible-collection-mssql.git

manifest:
  directives:
    - recursive-include roles/* *.md
    - recursive-include roles/*/files **
    - exclude galaxy.yml galaxy.yaml MANIFEST.json FILES.json *.tar.gz
    - recursive-exclude tests/output **
    - recursive-exclude roles/*/molecule **
    - recursive-exclude molecule **
    - global-exclude /.* /__pycache__
