---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: install
  description: This role installs Microsoft SQL Server.

  license: MIT

  min_ansible_version: '2.16'

  platforms:
    - name: EL
      versions:
        - '8'
        - '9'
    - name: Ubuntu
      versions:
        - jammy
    - name: Windows
      versions:
        - '2025'
        - '2022'
        - '2019'

collections:
  - ansible.posix
  - ansible.windows
  - chocolatey.chocolatey
  - community.general
  - community.hashi_vault
  - community.windows
  - trippsc2.hashi_vault
  - trippsc2.windows

dependencies: []
