---
_mssql_is_os_supported: true
_mssql_is_tested: true

_mssql_supported_server_versions:
  - '2017'
  - '2019'
  - '2022'

_mssql_default_firewall_type: firewalld

_mssql_default_database_backup_path: /var/opt/mssql/data

_mssql_prod_repo_url: https://packages.microsoft.com/rhel/8/prod/

_mssql_server_repo_url: >-
  https://packages.microsoft.com/rhel/8/mssql-server-{{ mssql_version }}/

_mssql_server_is_package_available_by_version:
  '2017': false
  '2019': true
  '2022': true

_mssql_server_is_package_available: "{{ _mssql_server_is_package_available_by_version[mssql_version] }}"
