---
_mssql_supported_server_versions:
  - '2019'
  - '2022'

_mssql_default_firewall_type: ufw

_mssql_default_database_backup_path: /var/opt/mssql/data

_mssql_prod_repo_url: https://packages.microsoft.com/ubuntu/20.04/prod

_mssql_server_repo_url: >-
  https://packages.microsoft.com/ubuntu/20.04/mssql-server-{{ mssql_version }}

_mssql_server_is_package_available_by_version:
  '2019': false
  '2022': true

_mssql_server_is_package_available: "{{ mssql_server_is_package_available_by_version[mssql_version] }}"
